# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Random posts!'
tagline:          'Blog Posts'

url:              https://mykezero.github.io
baseurl:          https://mykezero.github.io/

# url:              http://127.0.0.1:4000
# baseurl:          /

rss:              atom.xml

author:
  name:           Mykezero
  url:            https://github.com/Mykezero
  email:          mikebartron@gmail.com


paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://mykezero.github.io

# Gems
gems: [jekyll-paginate]
