# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mykezero
tagline:          'Blog Posts'
description:      'Random posts about random things!'
url:              https://mykezero.github.io
baseurl:          /

author:
  name:           'Mykezero'
  url:            https://github.com/Mykezero

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://mykezero.github.io
